version: '3'
services:
  web:
    build: ./app
    ports:
      - "5000:5000" 
    environment:
      - DB_HOST=db
      - DB_NAME=test_db
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: